### ISSUE TITLE
Missing step in the install instructions

### ISSUE THREAD

**Issue by multijoy** [MTz12/Samsung-ML-1640-Printer-Ventura-Apple-Silicon#1]
The readme file in the ML-1640 branch appears to miss the step about installing the *qpd files, which gives you "the driver was not installed correctly" error when you try to add the printer.

I followed that step having followed the rest of the readme and it cleared the error (and has resurrected my workhorse of a personal printer!)

**Comment by MTz12** [comment]
In the main branch, I provide a folder called "Samsung" in which the *qpdl files are located in a sub-folder called "UDP/Filters".

**Comment by multijoy** [comment]
Hi, found them fine - just the readme for the ML-1640 omits the step from the readme in the main!

**Comment by migmaia** [comment]
I followed in your footsteps. When I print the printer it prints a page saying INTERNAL ERRORS - Please use the proper driver. POSITION: 0x0 (0) 
SYSTEM: h6fw_5.49/xl_op 
LINE: 180 
VERSION: SPL 5.49 10-20-200
Can you help me?

**Comment by lopitec** [comment]
Hi, great project. Thank you. Could you provide a short summary how to adapt it for other Samsung printers. All of them are not supported by the vendor anymore. The last driver versions are available for OS X only

**Comment by MTz12** [comment]
> I followed in your footsteps. When I print the printer it prints a page saying INTERNAL ERRORS - Please use the proper driver. POSITION: 0x0 (0) SYSTEM: h6fw_5.49/xl_op LINE: 180 VERSION: SPL 5.49 10-20-200 Can you help me?

I'm sorry, I don't know what's wrong. Did you follow the instructions and which printer are you using?

**Comment by dekaru** [comment]
> The readme file in the ML-1640 branch appears to miss the step about installing the *qpd files, which gives you "the driver was not installed correctly" error when you try to add the printer.


Hello @multijoy, how does one go installing the *qpd files? Thank you :)

**Comment by philholden** [comment]
Awesome!!! Thanks @MTz12 my printer now works.
