### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alizborsa** [MTz12/Samsung-ML-1640-Printer-Ventura-Apple-Silicon#4]
![Screenshot 2023-10-09 at 18 28 23](https://github.com/MTz12/Samsung-ML-1640-Printer-Ventura-Apple-Silicon/assets/11886738/6266de6c-a42c-4ba7-91ec-b46de771b24c)

Hey,
 I am trying your method to make my printer print but I get this message. Could you please help me out, what is the issue now?
Thanks!

**Comment by MTz12** [comment]
I'm not sure I can help you. Did you follow the installation guide? Which printer are you using? Please provide a detailed overview of your installation procedure.
